import { Poppins } from 'next/font/google';
import './globals.css';
import ProtectedRoute from '@/components/ProtectedRoute';
import 'react-loading-skeleton/dist/skeleton.css';

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
});

export const metadata = {
  title: 'Home',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <ProtectedRoute>
      <html lang='en'>
        <body className={poppins.className}>{children}</body>
      </html>
    </ProtectedRoute>
  );
}
