import { Poppins } from 'next/font/google';
import { DashboardLayout } from '@/components/DashboardLayout';

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
});

export const metadata = {
  title: 'Dashboard',
  description: 'Generated by create next app',
};

export default function MainDashboard({ children }) {
  return (
    <html lang='en'>
      <body className={poppins.className}>
        <DashboardLayout>{children}</DashboardLayout>
      </body>
    </html>
  );
}
