export const metadata = {
  title: 'Transactions Page',
  description: 'Generated by create next app',
};

export default function TransactionsPage() {
  return (
    <>
      <div className='p-10 mx-auto my-10 max-w-7xl'>
        <p>Transactions Page</p>
        <p className='mt-10'>
          Lorem ipsum dolor, sit amet consectetur adipisicing elit. Aspernatur
          repellat maxime cupiditate reiciendis, accusantium exercitationem
          reprehenderit esse enim in doloribus ea beatae, pariatur, impedit modi
          hic veniam quod eaque incidunt fuga voluptatum tenetur facilis? Cumque
          amet possimus commodi ipsum quos alias iusto voluptate aut rerum
          facere velit optio atque quibusdam animi culpa at, aspernatur
          voluptatum eum sed deleniti? Eos non eveniet excepturi doloribus
          consequatur alias repellat sunt nobis delectus sequi. Similique
          pariatur, rerum deserunt mollitia repudiandae laborum dicta minus
          maxime. Quis perspiciatis cum voluptatum harum ipsa expedita molestias
          consequatur pariatur similique exercitationem, nemo soluta quam
          eligendi id omnis deserunt praesentium voluptate natus, perferendis,
          animi sunt ratione. Neque nisi perferendis temporibus recusandae
          labore nihil expedita non iusto. Illum minus incidunt in?
        </p>
      </div>
    </>
  );
}
